Justin unittests
hicsail/authentication-service pull request #26
Opened 2022-12-14 18:53 UTC by ch3njust1n

# Description

Unit tests for:
1. `/login/username`
2. `/login/email`
3. `/signup`
4. `/recover/forgot`

## Checklist

- [x] This PR can be reviewed in under 30 minutes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have assigned reviewers to this PR.

2022-12-14 19:06 UTC, cbolles requested changes
Looks good, one possible suggestion and one spare print to remove

2022-12-14 19:06 UTC, cbolles commented on packages/server/src/auth/auth.service.ts
> +    console.log(wasSet);
NIT: Remove extra `console.log`

2022-12-14 19:06 UTC, cbolles commented on packages/server/src/auth/auth.service.ts
> +    if (projectId != null && username != null && password != null) {
Something that may be an improvement. In the case where the arguments aren't provided, maybe have the status code be an `HttpStatus.BAD_REQUEST`. That ways users of the auth service can more easily debug their code.

2022-12-14 21:42 UTC, cbolles requested changes
Looks good, one possible suggestion and one spare print to remove

2022-12-14 21:46 UTC, cbolles submitted a review, later dismissed

2022-12-14 21:58 UTC, cbolles commented on packages/server/src/auth/auth.service.ts
> +    if (projectId != null && username != null && password != null) {
So my thought here was that `BAD_REQUEST` is returned if something is wrong with the format of the data and `UNAUTHORIZED` when authorization specifically fails. That way is easier to find out if the issue is genuinely the auth service not allowing access or if the issue is a malformed request

2022-12-14 21:58 UTC, cbolles reviewed
Looks good, have a clarification on my thought on the HTTP exception

2022-12-14 22:04 UTC, ch3njust1n commented on packages/server/src/auth/auth.service.ts
> +    if (projectId != null && username != null && password != null) {
Ah ok thanks for the clarification. That makes sense.

2022-12-16 19:10 UTC, cbolles approved these changes

2022-12-16 19:10 UTC, merged