add user and project decorators
hicsail/authentication-service pull request #62
Opened 2023-04-04 18:03 UTC by chrischo360

# Description

> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Checklist

- [ ] This PR can be reviewed in under 30 minutes
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned reviewers to this PR.

2023-04-04 19:06 UTC, cbolles requested changes

2023-04-04 19:06 UTC, cbolles commented on packages/server/src/user/user.decorator.ts
> +export const GetUser = createParamDecorator((data: unknown, ctx: ExecutionContext) => {
The `JwtAuthGuard` typically will add the user to the context so when using the decorators you can avoid having to re-decode the JWT token.

For example [here](https://github.com/hicsail/object-storage-service/blob/main/packages/server/src/auth/user.decorator.ts) is a decorator I wrote that grabs the user from the context. I then can use that decorator as long as the endpoint is protected by the JWT Guard like [so](https://github.com/hicsail/object-storage-service/blob/main/packages/server/src/perms/perms.resolver.ts#L21). 

That way there is a bit better error handling and you don't have to keep parsing the JWT.

2023-04-05 18:14 UTC, gregfrasco commented on packages/server/src/project/project.decorator.ts
> +  const token = request.headers.authorization.split(' ')[1];
```suggestion
  const token = req.headers?.authorization?.split(' ')[1];
```

Possibly no authorization or not space in header, have to handle that case

2023-05-08 20:00 UTC, gregfrasco commented
Close for now, new plans for the summer

2023-05-08 20:00 UTC, closed without merging