Google auth
hicsail/authentication-service pull request #70
Opened 2023-05-26 16:08 UTC by shashankkarthik

# Description

- Added Google Sign-In button to sign in page.
- Google Sign-In for existing users by matching emails.
- Google Sign-in for nonexistent users by creating new user from Google User data.

## Checklist

- [ ] This PR can be reviewed in under 30 minutes
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned reviewers to this PR.

2023-05-26 16:27 UTC, cbolles requested changes
Looks good, only a couple of minor suggestions on my end

2023-05-26 16:27 UTC, cbolles commented on packages/client/package.json
> +    "@react-oauth/google": "*",
Should this be a regular dependency?

2023-05-26 16:27 UTC, cbolles commented on packages/client/src/main.tsx
> +  <GoogleOAuthProvider clientId="920265659839-vu93dpp83vk1gaotvq5psjeeobjkbmlt.apps.googleusercontent.com">
That client ID looks like it should probably be an environment variable

2023-05-30 14:07 UTC, gregfrasco requested changes
Noce job, some minor changes

2023-05-30 14:07 UTC, gregfrasco commented on packages/client/src/main.tsx
> +  <GoogleOAuthProvider clientId="920265659839-vu93dpp83vk1gaotvq5psjeeobjkbmlt.apps.googleusercontent.com">
We should also put the provider inside of React.StrictMode and not above it, unless there is a reason to not be in strict mode

2023-05-30 14:07 UTC, gregfrasco commented on packages/client/src/pages/sign-in.tsx
> +        {project?.authMethods.emailAuth ? (
If you are conditionally rendering something where on condition renders null, use can just use the && operator
```suggestion
        {project?.authMethods.emailAuth && (
```
And then just close it
```
)}
```

2023-05-30 14:07 UTC, gregfrasco commented on packages/client/src/pages/sign-in.tsx
> +          {project?.authMethods.emailAuth ? (
You probably could include this in the emailAuth condition if you add a fragment to wrap both the form and the buttons.

2023-05-30 14:07 UTC, gregfrasco commented on packages/client/src/pages/sign-in.tsx
> +        <Grid container>
If this is a single item you don't need a grid, you could just use a box and add styling or a stack to help with layout

2023-05-30 14:07 UTC, gregfrasco commented on packages/client/src/pages/sign-in.tsx
> +                    pushMessage('Invalid Credentials');
This message should be more helpful to users
```suggestion
                    pushMessage('Unable to Authenticate with Google');
```

2023-05-30 14:07 UTC, gregfrasco commented on packages/server/src/auth/auth.service.ts
> +import { decode } from 'jsonwebtoken';
Not used

2023-05-30 14:07 UTC, gregfrasco commented on packages/server/src/auth/auth.service.ts
> +import { last, lastValueFrom } from 'rxjs';
last not used

2023-05-31 15:49 UTC, cbolles approved these changes, later dismissed

2023-05-31 16:20 UTC, gregfrasco commented on packages/server/src/auth/auth.service.ts
> +    }
Minor: you have validation thru decorators, so you should need to have it hear as well

2023-06-05 19:08 UTC, gregfrasco approved these changes

2023-06-05 19:18 UTC, merged